### ISSUE TITLE
Error klipper no conection...

### ISSUE THREAD

**Issue by BrendaIT** [Deutherius/VGB#2]
I have used it for a long time, I don't know why, it doesn't work anymore. klipper unable to reconnect after reboot. does anyone have any idea what the problem is? i think there is the deprecation of parameter sets from klipper. therefore it must be rechecked.

**Comment by Deutherius** [comment]
I don't think the issue is caused by parameter set deprecation in VGB, as VGB doesn't use any parameters, just variables (which is a different thing). Everything works fine on my printers, latest version of Klipper/Moonraker. Without a log file from Klipper and Moonraker I'm afraid I can't really help you further than that.

**Comment by BrendaIT** [comment]
Thanks for the reply! sorry could you help me .... i'm not so familiar with git ... how can i attach klippy files. log?

**Comment by BrendaIT** [comment]
I managed to attach the files .... at this moment I disabled VGB, but there are registers that can control them.

**Comment by Deutherius** [comment]
I can see one error complaining about missing klicky macros, but nothing concerning VGB. Can you enable VGB and send me the logs *after* the error happens?

**Comment by BrendaIT** [comment]
ok, I do now

**Comment by BrendaIT** [comment]
just done, and the usual error comes ... if I run the commands:
pi@raspberrypi:~ $ cd /home/pi/vgb
pi@raspberrypi:~/vgb $ python generate_VGB_meshes.py printer.cfg 0.2 7
Traceback (most recent call last):
  File "generate_VGB_meshes.py", line 4, in <module>
    import numpy as np
ImportError: No module named numpy

comes this messages. instead if I do:
 python3 generate_VGB_meshes.py printer.cfg 0.2 7
goes to good end.

**Comment by Deutherius** [comment]
Right. Running "python" means python2, generate_VGB_meshes.py needs to be run with python3. I should specify this in the readme.

However, I am unclear how this is related to Klipper disconnecting, or what could be causing Klipper to disconnect. There were some errors about missing bed meshes (I'm guessing you did not generate them yet), and you have generated extra meshes below and above your specified min and max temp (so you can actually set variable min_temp to 17.5 and max_temp to 55.3), but that shouldn't cause a Klipper disconnect.

**Comment by BrendaIT** [comment]
I tried various settings, without positive results ... I don't know what to do ... I'm sorry not to use it anymore, it was very convenient. I do other tests. thank you

**Comment by BrendaIT** [comment]
hi, i managed to find the main problem where it was interfering with restarting klipper.
to work without interference, after all the VGB processes a normal mesh must be created and saved as default, and that's it. klipper works perfectly with VGB.

**Comment by Deutherius** [comment]
Interesting, that would make sense. Is this an issue that was caused by VGB or its installation process specifically, or did you manually rename/delete the "default" bed mesh because it shouldn't technically be necessary anymore (when using VGB)?

**Comment by BrendaIT** [comment]
I probably didn't have any settings saved in the auto generated block, other than meshes, and it seems from what I understand, klipper did not recognize the meshes generated by generate_VGB_meshes.py, therefore it caused an error.
Then doing a mesh calibration after the generate_VGB_meshes.py process, Klipper recognizes the printer.cfg file and restarts normally. Fantasic !!!! I am happy to solve the problem. And so much that I use your VGB and I love it! You did a great job !!! Pecato that it is not so widely disclosed ...

**Comment by BrendaIT** [comment]
By the way, I am using VGB together with Frame Compensation, I would like to know if there is interference or something? What do you suggest me? Thanks!

**Comment by Deutherius** [comment]
By using VGB, you eliminate gantry bowing, which can be a big factor in perceived vertical frame expansion. Unfortunately it can't really be measured by how much, because bed meshes are not a factor when homing the machine (which is how you find out your thermal expansion coefficient for frame comp) - the gantry bowing effect itself still happens. In contrast, when you bolt on real physical gantry backers, they eliminate the gantry bowing effect in reality, and this can be seen in the thermal testing (your thermal expansion coefficient will be calculated as lower, mine went from 0.03 mm/K to 0.015 mm/K, for example - V2.4 300mm). You will have to guesstimate how much to tune down the expansion coefficient yourself I'm afraid, I have no clue how to calculate that at this point.

As far as I know, this is the only issue when using both frame comp and VGB, they should be perfectly compatible otherwise.

Glad you solved the issue, I'll put a note in the readme to keep one "default" mesh in there so Klipper is happy.
